---
title: "36-315 Homework 06, Fall 2016"
author: "Your Name Here"
date: "Due Wednesday, October 12, 2016 (12pm ET) on Blackboard"
output: 
  html_document:
    toc:  true
    toc_float:  true
    code_folding:  show
---

##  Homework 06:  Practice Lab Exam

***General instructions for all assignments***: 

+  Use this file as the template for your submission.  Delete the unnecessary text (e.g. this text, the problem statements, etc).  That said, keep the nicely formatted "Problem 1", "Problem 2", "a.", "b.", etc
+  Upload a single `R` Markdown file (named as:  [AndrewID]-HW06.Rmd -- e.g. "sventura-HW06.Rmd") to the Homework 06 submission section on Blackboard.  You do not need to upload the .html file.
+  The instructor and TAs will run your .Rmd file on their computer.  **If your .Rmd file does not knit on our computers, you will be automatically be deducted 10 points.**
+  Your file should contain the code to answer each question in its own code block.  Your code should produce plots/output that will be automatically embedded in the output (.html) file
+  Each answer must be supported by written statements (unless otherwise specified)
+  Include the name of anyone you collaborated with at the top of the assignment
+  Include the style guide you used below under Problem 0

***
***


#  Problem 0

**Style Guide and Table of Contents**

a.  What style guide are you using on this assignment?  (Up to 10 points will be deducted if you do not adhere to a specific style guide.)

b.  Remember to include a floating table of contents in your submission.

c.  Use your theme for all problems.


***
***


#  Instructions:  Practice Lab Exam

+  For all lab exam questions, be sure to answer the question(s) asked.
+  In addition to answering the questions, **write 1-3 sentences describing why you made certain choices in your graphic.**  For example, why did you choose a histogram vs. density plot?  Pie chart vs. rose diagram vs. bar chart vs. spine chart?  Stacked vs. side-by-side bar chart?  Why did you choose the bin width / number of bins in your histogram?  Why did you choose the bandwidth and kernel that you picked in your density plot?  Why did you decide to arrange the graphs the way you did (e.g. in a grid, horizontally, vertically).  Etc.
+  Remember, whenever you can supplement your answer with information from a statistical test, this is very beneficial!  Feel free to run statistical tests and include this information as part of your answer.


###  For all problems below, you should justify your answer with a single graph.

As always, using `facet_wrap()` or `facet_grid()` counts as one graph, while using `grid.arrange()` does not.




###  Data:  Museum of Modern Art (New York)

Load the Museum of Modern Art (MoMA) dataset from the course GitHub page, and store the data in an object called `moma`:  [https://raw.githubusercontent.com/sventura/315-code-and-datasets/master/data/moma.csv]

The data is provided by the Museum of Modern Art, and is described [here](https://github.com/MuseumofModernArt/collection).  The dataset you have access to is a highly modified subset of the original dataset.  The original data has been enriched with two additional variables, `Width` and `Height`.

***
***



#  Problem 1

(12 points)

**Departmental Favoritism?**

a.  Describe the distribution of the number of artworks in each department in MoMA.  Describe any interesting features you see.

b.  Would you say that the distribution of Department has any modes?  Would you say that it is skewed?  Explain your answer.

c.  (BONUS:  2 points)  Your friend says that MoMA aims to have 30% Drawings, 1% paiting/sculpture, 52% photography, and 17% prints and illustrated books.  Do you have any evidence to confirm or deny this claim?  Explain.



***
***



#  Problem 2

(12 points)

**Curator Bias?**

Is there any association between the type (`Classification`) of the artwork and whether or not it was approved by a curator?  Are curators more or less likely to have approved particular types of art in the collection? 



***
***



#  Problem 3

(20 points)

**Art Movements**

a.  Characterize the marginal distribution of the year in which the artwork was created (`Date`).  

b.  Are there any time periods with increases or decreases in the amount of artwork in MoMA?  Are there particular types of art that correspond to these increases or decreases?

c.  Would it be appropriate to say that the distribution of `Date` is Normal/Gaussian?  Why or why not?



***
***



#  Problem 4

(20 points)  

**Monthly Acquisitions**

You are an artist looking to sell a piece to MoMA.  (Good luck with that, by the way.)

a.  Describe the conditional distributions of the month MoMA acquired the artwork given the department for which it was acquired.  Are there particular months in the year when MoMA is more or less likely to acquire new artworks?  Does this change depending on the department for which the artwork was acquired?

b.  Your friend says that the month of acquisition and the department for which the artwork was acquired are independent.  Do you have any evidence to support or deny this claim?  Explain.


***
***



#  Problem 5

(16 points)  

**Untitled**

Find the subset of all artworks with the exact title "Untitled".  How many "Untitled" artworks are there, in total?  Does the frequency of "Untitled" artworks change depending on the decade in which the artwork was created?


***
***



#  Problem 6

(20 points)  

**The Famous Last Words**

Some people believe that artists become more popular after they die.  Let's see if there's any evidence that this is true.

Create a new variable called `date_delta` (or `date.delta`), which measures the number of years between when the artwork was created (`Date`) and when it was acquired by MoMA (first four characters of `DateAcquired`).  Store it in your `moma` `data.frame`.  

a.  Plot the `Date` vs. the `date_delta`, and describe the distribution you see.  Why does there appear to be a certain structure to the joint distribution of these two variables?  

b.  Are there any potential outliers in this dataset?  If so, identify the outliers and characterize them.



***
***

