---
title: "36-315 Lab 11:  Shiny + Group Project"
author: "Your Name Here"
date: "Due Friday, April 28th, 2017 (6:30pm)"
output: 
  html_document:
    toc:  true
    toc_float:  true
    code_folding:  show
---



#  Instructions

**This is a group assignment -- work with your group to complete the lab!**  

When turning this assignment in, only one group member should submit the lab.  

See Problem 5 for information on what to submit.



***
***



#  Oral Evaluation Graphics

Here are some graphs that you can use for your oral evaluations this week:
 
+  [Map of Gun Deaths in the US](http://data.huffingtonpost.com/2013/03/gun-deaths)
+  ["Beat the Fed"](http://graphics.wsj.com/beat-the-fed/)
+  ["The Billion Dollar Startup Club"](http://graphics.wsj.com/billion-dollar-club/)
+  [Job Market / Unemployment Tracker](http://graphics.wsj.com/job-market-tracker/)
+  [Human Trafficking](http://www.telegraph.co.uk/news/worldnews/northamerica/usa/11770294/Mapped-How-the-world-is-tackling-human-trafficking.html)
+  [Google Food Searches](http://rhythm-of-food.net/) (pick anything under "It's April! What's Asked for Right Now?")
+  [NBA Redraft Tool](http://polygraph.cool/redraft/) (the first interactive graphic)


***
***



#  Shiny Resources

Below is a list of resources with information on creating Shiny Apps.

+  [RStudio's Shiny Page](http://shiny.rstudio.com/).
+  [RStudio's Shiny Tutorials](http://shiny.rstudio.com/tutorial/).
+  [RStudio's Shiny Gallery (example Shiny apps, with source code)](http://shiny.rstudio.com/gallery/).
+  [RStudio's list of Shiny functions with descriptions](http://shiny.rstudio.com/reference/shiny/latest/).
+  [GitHub repository for Shannon and Lee's 1st-place public health hackathon Shiny App](https://github.com/shannong19/hackathon).  See the `server.R`, `ui.R`, and `global.R` files.
+  [GitHub repository for Tiffany's CMU FCE Shiny App (from lecture on Wednesday)](http://github.com/yeukyul/fce_visualizer).

Additionally, see the Lecture 25 R Demo for links on Shiny, Plotly, HTML Widgets, etc.


#  Problem 1

(0 points)

**Choose Your Data**

You get to pick your own dataset again!  

##  Sources

Here are some repositories with many, many datasets to choose from:

+  [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets.html)
+  [Kaggle](https://www.kaggle.com/datasets)
+  [Dream To Learn](https://dreamtolearn.com/ryan/1001_datasets)
+  [Google Public Data Explorer](https://www.google.com/publicdata/directory)
+  [The US Government](https://www.data.gov/)
+  [Stanford Statistics](http://statweb.stanford.edu/~sabatti/data.html)
+  [American Psychological Asosciation](http://www.apa.org/research/responsible/data-links.aspx)
+  [GitHub](https://github.com/caesar0301/awesome-public-datasets)
+  [FiveThirtyEight](https://github.com/fivethirtyeight/data)

You do not have to pick a dataset from one of these places.  These are just suggestions.


##  Requirements

1.  Your data must be contain a mix of categorical and continuous variables and be complex enough that you can create 8 interesting graphs (so datasets with only a few variables will not work).

2.  You CANNOT use any of the datasets that were used by any group from the static graphics group project.  These datasets were:

+  Airline Survey Data
+  2016 Rio Olympics
+  FiveThirtyEight Police Killings
+  UFO Sightings
+  Pokemon
+  1994 US Census Income
+  NBA History Data from FiveThirtyEight
+  NBA Rest API Data
+  NYC Crime Data
+  League of Legends 2016 World Championship Data
+  H1B Visa Dataset
+  Chicago Crime Reports
+  Lending Club Loan Data
+  Kaggle World Development Indicators
+  NYC Weather Data
+  2016 Presidential Election (I may allow this if there is strong interest)
+  Lahman / MLB History (I may allow this if there is strong interest)
+  Yelp Reviews
+  NASA / Astronauts
+  US Homicides
+  World University Rankings

If there is strong interest in using any of these datasets, talk to Sam ASAP.

3.  I'm strongly encouraging groups to pick different datasets, so that no group is using the same dataset.  If you choose a dataset that another group has already chosen, I may ask you to switch.

4.  Be sure to read the guidelines on the graphics below.  These will certainly influence what datasets you choose.

5.  You cannot use a dataset that you have used before in this class or in any other class.


##  Submission

Below under Problem 5.

***
***



#  Problem 2

(10 points)

**Sign Up For A Presentation Slot**

You can sign up for a presentation slot [here](www.google.com) (link will be posted on Friday at 1:00pm).

You do not have to turn anything in for this problem.

***
***


#  Problem 3

(70 points)

**Create Your Own Shiny App**

a.  (30 points)  Go to the first link under "Resources" above.  Under "Here is a Shiny App", you'll see the `ui.R` and `server.R` code.  Make a copy of these on your own computer.  Edit them so that they use `ggplot()` to create the histogram, density estimate, and rug plot.  Ensure that all of the existing interactive features are functional in your new version.

b.  (20 points)  Using the `faithful` dataset, create two additional graphics using the two variables in the `faithful` dataset:

+  Graph 1:  A scatterplot of `eruptions` vs. `waiting`.  The graph should be interactive in some way -- e.g. let the user specify the point size with a slider, let the user check a box to add a trend line (e.g. with `geom_smooth()`) to the plot, etc.
+  Graph 2:  A 2-D density estimate of `eruptions` vs. `waiting`, displayed as a heat map or a contour plot.  The graph should be interactive in some way -- e.g. let the user to change the bandwidth in each direction, let the user click a checkbox to add or remove the points or contour lines, etc.

c.  (15 points)  Presentation and organization matter!  Organize your app as follows:  

+  Include a dashboard in your app (see [here](https://rstudio.github.io/shinydashboard/get_started.html)).  
+  Separate part (a) and part (b) into their own menu items in the sidebar (i.e. one menu item for part (a), one for part (b)).
+  Put each graph in part (b) into its own tab (see [here](http://shiny.rstudio.com/articles/tabsets.html)).

d.  (5 points)  Have at least one group member create a free account on [ShinyApps.io](www.ShinyApps.io).  Upload your working ShinyApp to this public website.  Make note of the public link at which your ShinyApp can be accessed (you'll need to submit this in Problem 5.)

***
***


#  Problem 4

(0 points)

**Coordinate with Your Group!**

Coordinate with your group!  

+  Set a time to meet outside of lecture/lab.  
+  Set a plan for completing the necessary parts of the final project.  

You do not have to turn anything in for this problem.


***
***


#  Problem 5

(10 points)

**Name Your Team**

On Blackboard, have one group member submit a single .txt file with the following information:

+  Name and AndrewID of each group member
+  Group ID Number
+  Group Name -- be creative (but respectful)
+  A short description of the data that your group will use (1-3 sentences)
+  Links to dataset
+  Link to your ShinyApps.io page from Problem 3

**When turning this assignment in, only one group member should submit the lab.**


***
***

