---
title: "36-315 Lab 11:  Shiny + Group Project"
author: "Your Name Here"
date: "Due Friday, December 2nd, 2016 (6:30pm)"
output: 
  html_document:
    toc:  true
    toc_float:  true
    code_folding:  show
---



#  Instructions

**This is a group assignment -- work with your group to complete the lab!**  

When turning this assignment in, only one group member should submit the lab.  

Upload a single .zip file containing your `ui.R` and `server.R files`, plus the information requested in Problem 5 below.



***
***



#  Oral Evaluation Graphics

Here are some graphs that you can use for your oral evaluations this week:
 
+  [Map of Gun Deaths in the US](http://data.huffingtonpost.com/2013/03/gun-deaths)
+  ["Beat the Fed"](http://graphics.wsj.com/beat-the-fed/)
+  ["The Billion Dollar Startup Club"](http://graphics.wsj.com/billion-dollar-club/)
+  [Job Market / Unemployment Tracker](http://graphics.wsj.com/job-market-tracker/)
+  [Human Trafficking](http://www.telegraph.co.uk/news/worldnews/northamerica/usa/11770294/Mapped-How-the-world-is-tackling-human-trafficking.html)


***
***



#  Shiny Resources

Below is a list of resources with information on creating Shiny Apps.

+  [RStudio's Shiny Page](http://shiny.rstudio.com/).
+  [RStudio's Shiny Tutorials](http://shiny.rstudio.com/tutorial/).
+  [RStudio's Shiny Gallery (example Shiny apps, with source code)](http://shiny.rstudio.com/gallery/).
+  [RStudio's list of Shiny functions with descriptions](http://shiny.rstudio.com/reference/shiny/latest/).
+  [GitHub repository for Shannon's public health hackathon Shiny App (from lecture on Monday)](https://github.com/shannong19/hackathon).  See the `server.R`, `ui.R`, and `global.R` files.

Additionally, see the Lecture 25 R Demo for links on Shiny, Plotly, HTML Widgets, etc.


#  Problem 1

(0 points)

**Choose Your Data**

You get to pick your own dataset again!  

##  Sources

Here are some repositories with many, many datasets to choose from:

+  [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets.html)
+  [Kaggle](https://www.kaggle.com/datasets)
+  [Dream To Learn](https://dreamtolearn.com/ryan/1001_datasets)
+  [Google Public Data Explorer](https://www.google.com/publicdata/directory)
+  [The US Government](https://www.data.gov/)
+  [Stanford Statistics](http://statweb.stanford.edu/~sabatti/data.html)
+  [American Psychological Asosciation](http://www.apa.org/research/responsible/data-links.aspx)
+  [GitHub](https://github.com/caesar0301/awesome-public-datasets)

That said, you are welcome to use data from any reputable source, pending approval from Sam.


##  Requirements

1.  Your data must be contain a mix of categorical and continuous variables and be complex enough that you can create 8 interesting graphs (so datasets with only a few variables will not work).

2.  You CANNOT use any of the datasets that were used by any group from the static graphics group project.  These datasets were:

+  IMDB
+  Video Game Sales
+  nflscrapR 2015 (but other seasons are okay)
+  Kickstarter
+  Portuguese Secondary School Data
+  1994 Census Database
+  Pollution in the Continental US
+  World University Rankings
+  US Department of Education 2013 College Scorecard Data
+  MLB / PITCHf/X Datasets (but ask Sam if you want to do something with this)

3.  I'm strongly encouraging groups to pick different datasets, so that no group is using the same dataset.  If you choose a dataset that another group has already chosen, I may ask you to switch.

4.  Be sure to read the guidelines on the graphics below.  These will certainly influence what datasets you choose.


##  Submission

See below under Problem 5.


#  Problem 2

(0 points)

**Sign Up For A Presentation Slot**

You can sign up for a presentation slot [here](http://doodle.com/poll/kp236m6bpd92y6uy).

You do not have to turn anything in for this problem.


#  Problem 3

(90 points)

**Create Your Own Shiny App**

a.  (40 points)  Go to the first link under "Resources" above.  Under "Here is a Shiny App", you'll see the `ui.R` and `server.R` code.  Make a copy of these on your own computer.  Edit them so that they use `ggplot()` to create the histogram, density estimate, and rug plot.  Ensure that all of the existing interactive features are functional in your new version.

b.  (30 points)  Using the `faithful` dataset, create two additional graphics using the two variables in the `faithful` dataset:

+  Graph 1:  A scatterplot of `eruptions` vs. `waiting`.  The graph should be interactive in some way -- e.g. let the user specify the point size with a slider, let the user check a box to add a trend line (e.g. with `geom_smooth()`) to the plot, etc.
+  Graph 2:  A 2-D density estimate of `eruptions` vs. `waiting`, displayed as a heat map or a contour plot.  The graph should be interactive in some way -- e.g. let the user to change the bandwidth in each direction, let the user click a checkbox to add or remove the points or contour lines, etc.

c.  (20 points)  Presentation and organization matter!  Organize your app as follows:  

+  Include a dashboard in your app (see [here](https://rstudio.github.io/shinydashboard/get_started.html)).  
+  Separate part (a) and part (b) into their own menu items in the sidebar (i.e. one menu item for part (a), one for part (b)).
+  Put each graph in part (b) into its own tab (see [here](http://shiny.rstudio.com/articles/tabsets.html)).


***
***


#  Problem 4

(0 points)

**Coordinate with Your Group!**

Coordinate with your group!  

+  Set a time to meet outside of lecture/lab.  
+  Set a plan for completing the necessary parts of the final project.  

You do not have to turn anything in for this problem.


***
***


#  Problem 5

(10 points)

**Name Your Team**

When you submit your .zip folder containing your `ui.R` and `server.R` files, include a text file in your .zip folder that has all of the following information:

+  Name and AndrewID of each group member
+  Group ID Number
+  Group Name -- be creative (but respectful)
+  A short description of the data that your group will use (1-3 sentences)
+  Links to dataset

**When turning this assignment in, only one group member should submit the lab.**


***
***

